### ISSUE TITLE
Stylish only paints the result for one of the files.

### ISSUE THREAD

**Issue by FJLopezGarcia** [gonsfx/gulp-jscs-stylish#13]
Hi all,
Do you know the reason why when my gulp task analyze several files located under different paths, the stylish only paints the result for 1 of the files? I think the issue is due to use patterns under "src". Do you know how to fix it?

``` javascript
gulp.task('test:jscs', function () {
    log('Check JavaScript code style with JSCS');
    var noop = function () { };

    return gulp
        .src(['app/src/**/!(*.min.*).js',
                'app/widgets/**/!(*.min.*).js',
                'app.module.js'])
        .pipe($.jscs({
            fix: false, 
            configPath: 'app/test/.jscsrc'})
        )
        .on('error', noop)  // don't stop on error
        .pipe(stylish())  // log style errors
        .pipe(gulp.dest('app/test/resources/test_out/vet/jscs'));
});
```

**Comment by FJLopezGarcia** [comment]
any update?

**Comment by codepunkt** [comment]
@FJLopezGarcia Please try version `1.4.0`

**Comment by FJLopezGarcia** [comment]
I can see only 50 warnings. Do you know if this is the limit reported by console?

**Comment by codepunkt** [comment]
Let me try to understand. You use jscs without jshint and get 50 warnings in total, even though it should show more than 50? Are all 50 on a single file?

**Comment by codepunkt** [comment]
@FJLopezGarcia If this is still a thing, please reopen.
