### ISSUE TITLE
I can't use with gulp-load-plugins

### ISSUE THREAD

**Issue by ramasilveyra** [gonsfx/gulp-jscs-stylish#5]
I can't use this plugin with gulp-load-plugins. And I want to implement on my workflow :(

**Comment by codepunkt** [comment]
I don't understand. Can you elaborate?

What exactly do you want to do and why does it fail? Code examples could help.

**Comment by ramasilveyra** [comment]
In my gulpfile.js I use the plugin gulp-load-plugins to load any gulp plugins, and I do this to avoid having to write a require line per plugin (`var pluginName= require('gulp-pluginName');`). You can see [his docs](https://github.com/jackfranklin/gulp-load-plugins#usage) to understand better what I want to do with your plugin and gulp-load-plugins, it's very simple.
I can't find anyway to call your plugin without having to spend one require line exclusive to your plugin `var stylish = require('gulp-jscs-stylish');`.

Hope you could understand, my English is not very good. Thank you for your work!

**Comment by codepunkt** [comment]
I know `gulp-load-plugins` and use it myself regularly

When you have this:

``` javascript
var gulpLoadPlugins = require('gulp-load-plugins');
var plugins = gulpLoadPlugins();
```

Accessing with `plugins.jscsStylish()` doesn't work?

**Comment by ramasilveyra** [comment]
No, `plugins.jscsStylish()` doesn't work.

**Comment by codepunkt** [comment]
Will try when i find the time. Please bear with me.

**Comment by akreitals** [comment]
FYI working fine with `gulpLoadPlugins 0.10.0`. Also `0.7.1` and `0.6.0`' if that is any consequence.

**Comment by codepunkt** [comment]
I didn't have the time to look at it as of now because i've got tons of other stuff to do at the moment. Sorry!

Will keep you posted once i find the time.

Have you tried debugging the differences between the various `gulpLoadPlugins` versions?

**Comment by codepunkt** [comment]
@ramasilveyra whats the version of `gulp-load-plugins` you tried to use?

**Comment by ramasilveyra** [comment]
@gonsfx Now runs well, maybe it was a `gulp-load-plugins` thing
