### ISSUE TITLE
Invalid reporter error after running gulp task

### ISSUE THREAD

**Issue by KevinJannis** [gonsfx/gulp-jscs-stylish#7]
Hi,

I have a task with the following code, however I keep getting an error when I try to run it. 
I attached a code example.

``` javascript
return gulp.src(config.files.js.src)
    .pipe(jshint('.jshintrc'))
    .pipe(jscs())
    .on('error', function() {})
    .pipe(stylish.combineWithHintResults())
    .pipe(jshint.reporter('jshint-stylish'))
    .pipe(concat('scripts.js'));
```

Error I am getting:

``` bash
[16:58:24] Error in plugin 'gulp-jshint'
Message:
    Invalid reporter
```

K.

**Comment by codepunkt** [comment]
Did you install `jshint-stylish` as a dependency?

**Comment by KevinJannis** [comment]
Thanks, it is working now.
Is this documented somewhere?

I also had to install `jscs-jsdoc` manually.

K.

**Comment by dimerman** [comment]
:+1:

**Comment by harshahid** [comment]
Thanks :) It's working now..
Installed module jshint-style 👍
